CREATE TABLE users
(
    id         INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(128),
    last_name  VARCHAR(128),
    user_name  VARCHAR(128),
    password   VARCHAR(255),
    is_active   BOOLEAN
);